---
- name: Generate CKLB checklist from scan results
  hosts: "{{ my_host | default('default-host-group') }}"
  gather_facts: false
  become: false

  tasks:
    - name: build CKLB
      include_role:
        name: cklb_renderer
      tags: [validate]
