---
- name: Configure RHEL 9 Host with DISA STIG
  hosts: "{{ my_host | default('default_host_group') }}"
  become: true
  check_mode: "{{ 'validate' in ansible_run_tags or ansible_check_mode }}"
  ignore_errors: "{{ 'validate' in ansible_run_tags or ansible_check_mode }}"
  tasks:
    - name: RHEL 9 STIG
      import_role:
        name: rhel9STIG
      when: ansible_distribution_major_version == "9"
      tags: always
