---
- name: Configure RHEL 9 Host with DISA STIG
  hosts: "{{ my_host | default('demoserver') }}"
  become: true
  # DO NOT set ignore_task_failures to "yes" unless you're using Check mode. only set it on the CLI when using -C!
  ignore_errors: "{{ ignore_task_failures | default('no') | bool }}"
#  vars:
#    administrator_security_groups:
#      - wheel
#      - openaiken_owners
  collections:
    - community.general

  tasks:
    - name: RHEL 9 STIG
      include_role:
        name: rhel9STIG
      when: ansible_distribution_major_version == "9"
