---
- name: RHEL 9 STIG supplement checks
  hosts: "{{ my_host | default('default_host_group') }}"
  become: true
  ignore_errors: "{{ ignore_task_failures | default('no') | bool }}"

  tasks:
    - name: RHEL 9 STIG supplement
      include_role:
        name: rhel9_stig_supplement
      tags: always
