---
# ─── Supplement Checks ────────────────────────────────────────────────────────
# Set to false to skip a supplement check entirely.
supp_rules:
  # CAT II   RHEL 9 must display the Standard Mandatory DOD Notice and Consent Bann
  RHEL-09-171011: true
  # CAT I    RHEL 9 must be a vendor-supported release.
  RHEL-09-211010: true
  # CAT II   RHEL 9 vendor packaged system security patches and updates must be ins
  RHEL-09-211015: true
  # CAT II   The graphical display manager must not be the default target on RHEL 9
  RHEL-09-211030: true
  # CAT III  RHEL 9 must enable the hardware random number generator entropy gather
  RHEL-09-211035: true
  # CAT I    The systemd Ctrl-Alt-Delete burst key sequence in RHEL 9 must be disab
  RHEL-09-211045: true
  # CAT II   RHEL 9 must require a boot loader superuser password.
  RHEL-09-212010: true
  # CAT II   RHEL 9 must disable the ability of systemd to spawn an interactive boo
  RHEL-09-212015: true
  # CAT I    RHEL 9 must require a unique superusers name upon booting into single-
  RHEL-09-212020: true
  # CAT II   RHEL 9 must disable virtual system calls.
  RHEL-09-212035: true
  # CAT II   RHEL 9 must clear the page allocator to prevent use-after-free attacks
  RHEL-09-212040: true
  # CAT II   RHEL 9 must clear memory when it is freed to prevent use-after-free at
  RHEL-09-212045: true
  # CAT III  RHEL 9 must enable mitigations against processor-based vulnerabilities
  RHEL-09-212050: true
  # CAT III  RHEL 9 must enable auditing of processes that start prior to the audit
  RHEL-09-212055: true
  # CAT II   RHEL 9 must implement nonexecutable data to protect its memory from un
  RHEL-09-213110: true
  # CAT II   RHEL 9 must ensure cryptographic verification of vendor software packa
  RHEL-09-214010: true
  # CAT I    RHEL 9 must have GPG signature verification enabled for all software r
  RHEL-09-214025: true
  # CAT II   RHEL 9 must be configured so that the cryptographic hashes of system f
  RHEL-09-214030: true
  # CAT I    RHEL 9 must not have a File Transfer Protocol (FTP) server package ins
  RHEL-09-215015: true
  # CAT I    The Trivial File Transfer Protocol (TFTP) server must not be installed
  RHEL-09-215060: true
  # CAT II   A graphical display manager must not be installed on RHEL 9 unless app
  RHEL-09-215070: true
  # CAT I    RHEL 9 must implement a FIPS 140-3-compliant systemwide cryptographic 
  RHEL-09-215105: true
  # CAT II   A separate RHEL 9 file system must be used for user home directories (
  RHEL-09-231010: true
  # CAT II   RHEL 9 must use a separate file system for /tmp.
  RHEL-09-231015: true
  # CAT III  RHEL 9 must use a separate file system for /var.
  RHEL-09-231020: true
  # CAT III  RHEL 9 must use a separate file system for /var/log.
  RHEL-09-231025: true
  # CAT III  RHEL 9 must use a separate file system for the system audit data path.
  RHEL-09-231030: true
  # CAT II   RHEL 9 must use a separate file system for /var/tmp.
  RHEL-09-231035: true
  # CAT II   RHEL 9 file system automount function must be disabled unless required
  RHEL-09-231040: true
  # CAT II   RHEL 9 must prevent device files from being interpreted on file system
  RHEL-09-231045: true
  # CAT II   RHEL 9 must prevent files with the setuid and setgid bit set from bein
  RHEL-09-231050: true
  # CAT II   RHEL 9 must prevent code from being executed on file systems that cont
  RHEL-09-231055: true
  # CAT II   RHEL 9 must prevent special devices on file systems that are imported 
  RHEL-09-231065: true
  # CAT II   RHEL 9  must prevent code from being executed on file systems that are
  RHEL-09-231070: true
  # CAT II   RHEL 9 must prevent files with the setuid and setgid bit set from bein
  RHEL-09-231075: true
  # CAT II   RHEL 9 must prevent code from being executed on file systems that are 
  RHEL-09-231080: true
  # CAT II   RHEL 9 must prevent special devices on file systems that are used with
  RHEL-09-231085: true
  # CAT II   RHEL 9 must prevent files with the setuid and setgid bit set from bein
  RHEL-09-231090: true
  # CAT II   RHEL 9 must mount /boot with the nodev option.
  RHEL-09-231095: true
  # CAT II   RHEL 9 must prevent files with the setuid and setgid bit set from bein
  RHEL-09-231100: true
  # CAT II   RHEL 9 must prevent files with the setuid and setgid bit set from bein
  RHEL-09-231105: true
  # CAT II   RHEL 9 must mount /dev/shm with the nodev option.
  RHEL-09-231110: true
  # CAT II   RHEL 9 must mount /dev/shm with the noexec option.
  RHEL-09-231115: true
  # CAT II   RHEL 9 must mount /dev/shm with the nosuid option.
  RHEL-09-231120: true
  # CAT II   RHEL 9 must mount /tmp with the nodev option.
  RHEL-09-231125: true
  # CAT II   RHEL 9 must mount /tmp with the noexec option.
  RHEL-09-231130: true
  # CAT II   RHEL 9 must mount /tmp with the nosuid option.
  RHEL-09-231135: true
  # CAT II   RHEL 9 must mount /var with the nodev option.
  RHEL-09-231140: true
  # CAT II   RHEL 9 must mount /var/log with the nodev option.
  RHEL-09-231145: true
  # CAT II   RHEL 9 must mount /var/log with the noexec option.
  RHEL-09-231150: true
  # CAT II   RHEL 9 must mount /var/log with the nosuid option.
  RHEL-09-231155: true
  # CAT II   RHEL 9 must mount /var/log/audit with the nodev option.
  RHEL-09-231160: true
  # CAT II   RHEL 9 must mount /var/log/audit with the noexec option.
  RHEL-09-231165: true
  # CAT II   RHEL 9 must mount /var/log/audit with the nosuid option.
  RHEL-09-231170: true
  # CAT II   RHEL 9 must mount /var/tmp with the nodev option.
  RHEL-09-231175: true
  # CAT II   RHEL 9 must mount /var/tmp with the noexec option.
  RHEL-09-231180: true
  # CAT II   RHEL 9 must mount /var/tmp with the nosuid option.
  RHEL-09-231185: true
  # CAT I    RHEL 9 local disk partitions must implement cryptographic mechanisms t
  RHEL-09-231190: true
  # CAT II   RHEL 9 must prevent special devices on non-root local partitions.
  RHEL-09-231200: true
  # CAT II   RHEL 9 system commands must have mode 755 or less permissive.
  RHEL-09-232010: true
  # CAT II   RHEL 9 library directories must have mode 755 or less permissive.
  RHEL-09-232015: true
  # CAT II   RHEL 9 library files must have mode 755 or less permissive.
  RHEL-09-232020: true
  # CAT II   RHEL 9 audit tools must have a mode of 0755 or less permissive.
  RHEL-09-232035: true
  # CAT II   RHEL 9 permissions of cron configuration files and directories must no
  RHEL-09-232040: true
  # CAT II   All RHEL 9 local initialization files must have mode 0740 or less perm
  RHEL-09-232045: true
  # CAT II   All RHEL 9 local interactive user home directories must have mode 0750
  RHEL-09-232050: true
  # CAT II   RHEL 9 "/etc/audit/" must be owned by root.
  RHEL-09-232103: true
  # CAT II   RHEL 9 "/etc/audit/" must be group-owned by root.
  RHEL-09-232104: true
  # CAT II   RHEL 9 system commands must be owned by root.
  RHEL-09-232190: true
  # CAT II   RHEL 9 system commands must be group-owned by root or a system account
  RHEL-09-232195: true
  # CAT II   RHEL 9 library files must be owned by root.
  RHEL-09-232200: true
  # CAT II   RHEL 9 library files must be group-owned by root or a system account.
  RHEL-09-232205: true
  # CAT II   RHEL 9 library directories must be owned by root.
  RHEL-09-232210: true
  # CAT II   RHEL 9 library directories must be group-owned by root or a system acc
  RHEL-09-232215: true
  # CAT II   RHEL 9 audit tools must be owned by root.
  RHEL-09-232220: true
  # CAT II   RHEL 9 audit tools must be group-owned by root.
  RHEL-09-232225: true
  # CAT II   RHEL 9 cron configuration files directory must be owned by root.
  RHEL-09-232230: true
  # CAT II   RHEL 9 cron configuration files directory must be group-owned by root.
  RHEL-09-232235: true
  # CAT II   All RHEL 9 world-writable directories must be owned by root, sys, bin,
  RHEL-09-232240: true
  # CAT II   A sticky bit must be set on all RHEL 9 public directories.
  RHEL-09-232245: true
  # CAT II   All RHEL 9 local files and directories must have a valid group owner.
  RHEL-09-232250: true
  # CAT II   All RHEL 9 local files and directories must have a valid owner.
  RHEL-09-232255: true
  # CAT II   RHEL 9 must be configured so that all system device files are correctl
  RHEL-09-232260: true
  # CAT II   The RHEL 9 firewall must employ a deny-all, allow-by-exception policy 
  RHEL-09-251020: true
  # CAT II   RHEL 9 must be configured to prohibit or restrict the use of functions
  RHEL-09-251035: true
  # CAT II   RHEL 9 network interfaces must not be in promiscuous mode.
  RHEL-09-251040: true
  # CAT II   RHEL 9 must securely compare internal information system clocks at lea
  RHEL-09-252020: true
  # CAT II   RHEL 9 systems using Domain Name Servers (DNS) resolution must have at
  RHEL-09-252035: true
  # CAT II   RHEL 9 must not have unauthorized IP tunnels configured.
  RHEL-09-252045: true
  # CAT II   RHEL 9 must be configured to prevent unrestricted mail relaying.
  RHEL-09-252050: true
  # CAT II   RHEL 9 must forward mail from postmaster to the root account using a p
  RHEL-09-252060: true
  # CAT I    There must be no shosts.equiv files on RHEL 9.
  RHEL-09-252070: true
  # CAT I    There must be no .shosts files on RHEL 9.
  RHEL-09-252075: true
  # CAT I    The RHEL 9 SSH client must be configured to use only DOD-approved encr
  RHEL-09-255064: true
  # CAT I    The RHEL 9 SSH server must be configured to use only DOD-approved encr
  RHEL-09-255065: true
  # CAT I    The RHEL 9 SSH client must be configured to use only DOD-approved Mess
  RHEL-09-255070: true
  # CAT I    The RHEL 9 SSH server must be configured to use only Message Authentic
  RHEL-09-255075: true
  # CAT II   RHEL 9 SSH server configuration files' permissions must not be modifie
  RHEL-09-255115: true
  # CAT II   RHEL 9 SSH private host key files must have mode 0600 or less permissi
  RHEL-09-255120: true
  # CAT II   RHEL 9 SSH public host key files must have mode 0644 or less permissiv
  RHEL-09-255125: true
  # CAT II   RHEL 9 must display the Standard Mandatory DOD Notice and Consent Bann
  RHEL-09-271010: true
  # CAT II   RHEL 9 must prevent a user from overriding the banner-message-enable s
  RHEL-09-271015: true
  # CAT II   RHEL 9 must disable the graphical user interface automount function un
  RHEL-09-271020: true
  # CAT II   RHEL 9 must prevent a user from overriding the disabling of the graphi
  RHEL-09-271025: true
  # CAT II   RHEL 9 must disable the graphical user interface autorun function unle
  RHEL-09-271030: true
  # CAT II   RHEL 9 must prevent a user from overriding the disabling of the graphi
  RHEL-09-271035: true
  # CAT I    RHEL 9 must not allow unattended or automatic logon via the graphical 
  RHEL-09-271040: true
  # CAT II   RHEL 9 must be able to initiate directly a session lock for all connec
  RHEL-09-271045: true
  # CAT II   RHEL 9 must prevent a user from overriding the disabling of the graphi
  RHEL-09-271050: true
  # CAT II   RHEL 9 must enable a user session lock until that user re-establishes 
  RHEL-09-271055: true
  # CAT II   RHEL 9 must prevent a user from overriding the screensaver lock-enable
  RHEL-09-271060: true
  # CAT II   RHEL 9 must automatically lock graphical user sessions after 10 minute
  RHEL-09-271065: true
  # CAT II   RHEL 9 must prevent a user from overriding the session idle-delay sett
  RHEL-09-271070: true
  # CAT II   RHEL 9 must initiate a session lock for graphical user interfaces when
  RHEL-09-271075: true
  # CAT II   RHEL 9 must prevent a user from overriding the session lock-delay sett
  RHEL-09-271080: true
  # CAT II   RHEL 9 must conceal, via the session lock, information previously visi
  RHEL-09-271085: true
  # CAT II   RHEL 9 effective dconf policy must match the policy keyfiles.
  RHEL-09-271090: true
  # CAT II   RHEL 9 must disable the ability of a user to restart the system from t
  RHEL-09-271095: true
  # CAT II   RHEL 9 must prevent a user from overriding the disable-restart-buttons
  RHEL-09-271100: true
  # CAT II   RHEL 9 must disable the ability of a user to accidentally press Ctrl-A
  RHEL-09-271105: true
  # CAT II   RHEL 9 must prevent a user from overriding the Ctrl-Alt-Del sequence s
  RHEL-09-271110: true
  # CAT II   RHEL 9 must disable the user list at logon for graphical user interfac
  RHEL-09-271115: true
  # CAT II   RHEL 9 must block unauthorized peripherals before establishing a conne
  RHEL-09-291030: true
  # CAT II   RHEL 9 wireless network adapters must be disabled.
  RHEL-09-291040: true
  # CAT II   RHEL 9 user account passwords must have a 60-day maximum password life
  RHEL-09-411015: true
  # CAT II   RHEL 9 must set the umask value to 077 for all local interactive user 
  RHEL-09-411025: true
  # CAT II   RHEL 9 duplicate User IDs (UIDs) must not exist for interactive users.
  RHEL-09-411030: true
  # CAT II   RHEL 9 system accounts must not have an interactive login shell.
  RHEL-09-411035: true
  # CAT II   RHEL 9 must automatically expire temporary accounts within 72 hours.
  RHEL-09-411040: true
  # CAT II   All RHEL 9 interactive users must have a primary group that exists.
  RHEL-09-411045: true
  # CAT II   RHEL 9 must disable account identifiers (individuals, groups, roles, a
  RHEL-09-411050: true
  # CAT II   Executable search paths within the initialization files of all local i
  RHEL-09-411055: true
  # CAT II   All RHEL 9 local interactive users must have a home directory assigned
  RHEL-09-411060: true
  # CAT II   All RHEL 9 local interactive user home directories defined in the /etc
  RHEL-09-411065: true
  # CAT II   All RHEL 9 local interactive user home directories must be group-owned
  RHEL-09-411070: true
  # CAT II   RHEL 9 must not have unauthorized accounts.
  RHEL-09-411095: true
  # CAT I    The root account must be the only account having unrestricted access t
  RHEL-09-411100: true
  # CAT II   RHEL 9 groups must have unique Group ID (GID).
  RHEL-09-411110: true
  # CAT II   RHEL 9 must automatically exit interactive command shell user sessions
  RHEL-09-412035: true
  # CAT II   RHEL 9 must terminate idle user sessions.
  RHEL-09-412080: true
  # CAT II   RHEL 9 must elevate the SELinux context when an administrator calls th
  RHEL-09-431016: true
  # CAT II   RHEL 9 must configure SELinux context type to allow the use of a nonde
  RHEL-09-431020: true
  # CAT II   RHEL 9 must use the invoking user's password for privilege escalation 
  RHEL-09-432020: true
  # CAT II   RHEL 9 must require users to reauthenticate for privilege escalation.
  RHEL-09-432025: true
  # CAT II   RHEL 9 must restrict privilege elevation to authorized personnel.
  RHEL-09-432030: true
  # CAT II   RHEL 9 must restrict the use of the "su" command.
  RHEL-09-432035: true
  # CAT II   The RHEL 9 fapolicy module must be configured to employ a deny-all, pe
  RHEL-09-433016: true
  # CAT II   RHEL 9 must ensure the password complexity module in the system-auth f
  RHEL-09-611010: true
  # CAT I    RHEL 9 must not allow blank or null passwords.
  RHEL-09-611025: true
  # CAT II   RHEL 9 must configure the use of the pam_faillock.so module in the /et
  RHEL-09-611030: true
  # CAT II   RHEL 9 must configure the use of the pam_faillock.so module in the /et
  RHEL-09-611035: true
  # CAT II   RHEL 9 must ensure the password complexity module is enabled in the pa
  RHEL-09-611040: true
  # CAT II   RHEL 9 must ensure the password complexity module is enabled in the sy
  RHEL-09-611045: true
  # CAT II   RHEL 9 password-auth must be configured to use a sufficient number of 
  RHEL-09-611050: true
  # CAT II   RHEL 9 system-auth must be configured to use a sufficient number of ha
  RHEL-09-611055: true
  # CAT II   RHEL 9 passwords must have a 24 hours minimum password lifetime restri
  RHEL-09-611080: true
  # CAT II   RHEL 9 must require users to provide a password for privilege escalati
  RHEL-09-611085: true
  # CAT II   RHEL 9 must not be configured to bypass password requirements for priv
  RHEL-09-611145: true
  # CAT II   RHEL 9 must not have accounts configured with blank or null passwords.
  RHEL-09-611155: true
  # CAT II   RHEL 9 must implement certificate status checking for multifactor auth
  RHEL-09-611170: true
  # CAT II   RHEL 9, for PKI-based authentication, must enforce authorized access t
  RHEL-09-611190: true
  # CAT II   RHEL 9 must require authentication to access single-user mode.
  RHEL-09-611200: true
  # CAT II   RHEL 9, for PKI-based authentication, must validate certificates by co
  RHEL-09-631010: true
  # CAT II   RHEL 9 must map the authenticated identity to the user or group accoun
  RHEL-09-631015: true
  # CAT II   RHEL 9 must have the AIDE package installed.
  RHEL-09-651010: true
  # CAT II   RHEL 9 must routinely check the baseline configuration for unauthorize
  RHEL-09-651015: true
  # CAT II   RHEL 9 must use a file integrity tool that is configured to use FIPS 1
  RHEL-09-651020: true
  # CAT II   RHEL 9 must use cryptographic mechanisms to protect the integrity of a
  RHEL-09-651025: true
  # CAT III  RHEL 9 must be configured so that the file integrity tool verifies Acc
  RHEL-09-651030: true
  # CAT III  RHEL 9 must be configured so that the file integrity tool verifies ext
  RHEL-09-651035: true
  # CAT II   RHEL 9 must be configured so that the rsyslog daemon does not accept l
  RHEL-09-652025: true
  # CAT II   RHEL 9 must be configured to forward audit records via TCP to a differ
  RHEL-09-652055: true
  # CAT II   RHEL 9 must allocate audit record storage capacity to store at least o
  RHEL-09-653030: true
  # CAT II   RHEL 9 audit logs must be group-owned by root or by a restricted loggi
  RHEL-09-653080: true
  # CAT II   RHEL 9 audit log directory must be owned by root to prevent unauthoriz
  RHEL-09-653085: true
  # CAT II   RHEL 9 audit logs file must have mode 0600 or less permissive to preve
  RHEL-09-653090: true
  # CAT II   RHEL 9 must allow only the information system security manager (ISSM) 
  RHEL-09-653110: true
  # CAT III  RHEL 9 must allocate an audit_backlog_limit of sufficient size to capt
  RHEL-09-653120: true
  # CAT II   RHEL 9 must have mail aliases to notify the information system securit
  RHEL-09-653125: true
  # CAT II   Successful/unsuccessful uses of the umount system call in RHEL 9 must 
  RHEL-09-654205: true
  # CAT II   Successful/unsuccessful uses of the umount2 system call in RHEL 9 must
  RHEL-09-654210: true
  # CAT I    RHEL 9 must enable FIPS mode.
  RHEL-09-671010: true
  # CAT II   RHEL 9 must employ FIPS 140-3-approved cryptographic hashing algorithm
  RHEL-09-671015: true
  # CAT I    RHEL 9 IP tunnels must use FIPS 140-3 approved cryptographic algorithm
  RHEL-09-671020: true
  # CAT II   RHEL 9 pam_unix.so module must be configured in the password-auth file
  RHEL-09-671025: true
  # CAT I    RHEL 9 cryptographic policy must not be overridden.
  RHEL-09-672020: true
  # CAT I    RHEL 9 must implement DOD-approved encryption in the bind package.
  RHEL-09-672050: true
