---
- name: set supplement run timestamp
  set_fact:
    supp_run_ts: "{{ '%y%b%d-%H:%M' | strftime }}"
  delegate_to: localhost
  become: false
  tags: always

- name: initialize supplement facts accumulator
  set_fact:
    supp_facts: {}
  tags: always

- import_tasks: RHEL-09-211010.yml
  tags: [RHEL-09-211010]
  when: supp_rules['RHEL-09-211010'] | default(true) | bool

- name: write supplement facts to disk
  copy:
    content: "{{ supp_facts | to_nice_json(indent=2) }}"
    dest: "{{ supp_facts_dir }}/{{ supp_run_ts }}-{{ inventory_hostname }}.json"
  delegate_to: localhost
  become: false
  tags: always
