---
- name: set supplement run timestamp
  set_fact:
    supp_run_ts: "{{ '%y%b%d-%H:%M' | strftime }}"
  delegate_to: localhost
  become: false
  tags: always

- name: initialize supplement facts accumulator
  set_fact:
    supp_facts: {}
  tags: always

- import_tasks: 211/RHEL-09-211010.yml
  tags: [RHEL-09-211010]
  when: supp_rules['RHEL-09-211010'] | default(true) | bool

- import_tasks: 211/RHEL-09-211015.yml
  tags: [RHEL-09-211015]
  when: supp_rules['RHEL-09-211015'] | default(true) | bool

- import_tasks: 211/RHEL-09-211030.yml
  tags: [RHEL-09-211030]
  when: supp_rules['RHEL-09-211030'] | default(true) | bool

- import_tasks: 211/RHEL-09-211035.yml
  tags: [RHEL-09-211035]
  when: supp_rules['RHEL-09-211035'] | default(true) | bool

- import_tasks: 211/RHEL-09-211045.yml
  tags: [RHEL-09-211045]
  when: supp_rules['RHEL-09-211045'] | default(true) | bool

- import_tasks: 212/RHEL-09-212010.yml
  tags: [RHEL-09-212010]
  when: supp_rules['RHEL-09-212010'] | default(true) | bool

- import_tasks: 212/RHEL-09-212015.yml
  tags: [RHEL-09-212015]
  when: supp_rules['RHEL-09-212015'] | default(true) | bool

- import_tasks: 212/RHEL-09-212020.yml
  tags: [RHEL-09-212020]
  when: supp_rules['RHEL-09-212020'] | default(true) | bool

- import_tasks: 212/RHEL-09-212035.yml
  tags: [RHEL-09-212035]
  when: supp_rules['RHEL-09-212035'] | default(true) | bool

- import_tasks: 212/RHEL-09-212040.yml
  tags: [RHEL-09-212040]
  when: supp_rules['RHEL-09-212040'] | default(true) | bool

- import_tasks: 212/RHEL-09-212045.yml
  tags: [RHEL-09-212045]
  when: supp_rules['RHEL-09-212045'] | default(true) | bool

- import_tasks: 212/RHEL-09-212050.yml
  tags: [RHEL-09-212050]
  when: supp_rules['RHEL-09-212050'] | default(true) | bool

- import_tasks: 212/RHEL-09-212055.yml
  tags: [RHEL-09-212055]
  when: supp_rules['RHEL-09-212055'] | default(true) | bool

- import_tasks: 213/RHEL-09-213110.yml
  tags: [RHEL-09-213110]
  when: supp_rules['RHEL-09-213110'] | default(true) | bool

- import_tasks: 214/RHEL-09-214010.yml
  tags: [RHEL-09-214010]
  when: supp_rules['RHEL-09-214010'] | default(true) | bool

- import_tasks: 214/RHEL-09-214025.yml
  tags: [RHEL-09-214025]
  when: supp_rules['RHEL-09-214025'] | default(true) | bool

- import_tasks: 214/RHEL-09-214030.yml
  tags: [RHEL-09-214030]
  when: supp_rules['RHEL-09-214030'] | default(true) | bool

- import_tasks: 215/RHEL-09-215015.yml
  tags: [RHEL-09-215015]
  when: supp_rules['RHEL-09-215015'] | default(true) | bool

- import_tasks: 215/RHEL-09-215060.yml
  tags: [RHEL-09-215060]
  when: supp_rules['RHEL-09-215060'] | default(true) | bool

- import_tasks: 215/RHEL-09-215070.yml
  tags: [RHEL-09-215070]
  when: supp_rules['RHEL-09-215070'] | default(true) | bool

- import_tasks: 215/RHEL-09-215105.yml
  tags: [RHEL-09-215105]
  when: supp_rules['RHEL-09-215105'] | default(true) | bool

- import_tasks: 231/RHEL-09-231010.yml
  tags: [RHEL-09-231010]
  when: supp_rules['RHEL-09-231010'] | default(true) | bool

- import_tasks: 231/RHEL-09-231015.yml
  tags: [RHEL-09-231015]
  when: supp_rules['RHEL-09-231015'] | default(true) | bool

- import_tasks: 231/RHEL-09-231020.yml
  tags: [RHEL-09-231020]
  when: supp_rules['RHEL-09-231020'] | default(true) | bool

- import_tasks: 231/RHEL-09-231025.yml
  tags: [RHEL-09-231025]
  when: supp_rules['RHEL-09-231025'] | default(true) | bool

- import_tasks: 231/RHEL-09-231030.yml
  tags: [RHEL-09-231030]
  when: supp_rules['RHEL-09-231030'] | default(true) | bool

- import_tasks: 231/RHEL-09-231035.yml
  tags: [RHEL-09-231035]
  when: supp_rules['RHEL-09-231035'] | default(true) | bool

- import_tasks: 231/RHEL-09-231040.yml
  tags: [RHEL-09-231040]
  when: supp_rules['RHEL-09-231040'] | default(true) | bool

- import_tasks: 231/RHEL-09-231045.yml
  tags: [RHEL-09-231045]
  when: supp_rules['RHEL-09-231045'] | default(true) | bool

- import_tasks: 231/RHEL-09-231050.yml
  tags: [RHEL-09-231050]
  when: supp_rules['RHEL-09-231050'] | default(true) | bool

- import_tasks: 231/RHEL-09-231055.yml
  tags: [RHEL-09-231055]
  when: supp_rules['RHEL-09-231055'] | default(true) | bool

- import_tasks: 231/RHEL-09-231065.yml
  tags: [RHEL-09-231065]
  when: supp_rules['RHEL-09-231065'] | default(true) | bool

- import_tasks: 231/RHEL-09-231070.yml
  tags: [RHEL-09-231070]
  when: supp_rules['RHEL-09-231070'] | default(true) | bool

- import_tasks: 231/RHEL-09-231075.yml
  tags: [RHEL-09-231075]
  when: supp_rules['RHEL-09-231075'] | default(true) | bool

- import_tasks: 231/RHEL-09-231080.yml
  tags: [RHEL-09-231080]
  when: supp_rules['RHEL-09-231080'] | default(true) | bool

- import_tasks: 231/RHEL-09-231085.yml
  tags: [RHEL-09-231085]
  when: supp_rules['RHEL-09-231085'] | default(true) | bool

- import_tasks: 231/RHEL-09-231090.yml
  tags: [RHEL-09-231090]
  when: supp_rules['RHEL-09-231090'] | default(true) | bool

- import_tasks: 231/RHEL-09-231095.yml
  tags: [RHEL-09-231095]
  when: supp_rules['RHEL-09-231095'] | default(true) | bool

- import_tasks: 231/RHEL-09-231100.yml
  tags: [RHEL-09-231100]
  when: supp_rules['RHEL-09-231100'] | default(true) | bool

- import_tasks: 231/RHEL-09-231105.yml
  tags: [RHEL-09-231105]
  when: supp_rules['RHEL-09-231105'] | default(true) | bool

- import_tasks: 231/RHEL-09-231110.yml
  tags: [RHEL-09-231110]
  when: supp_rules['RHEL-09-231110'] | default(true) | bool

- import_tasks: 231/RHEL-09-231115.yml
  tags: [RHEL-09-231115]
  when: supp_rules['RHEL-09-231115'] | default(true) | bool

- import_tasks: 231/RHEL-09-231120.yml
  tags: [RHEL-09-231120]
  when: supp_rules['RHEL-09-231120'] | default(true) | bool

- import_tasks: 231/RHEL-09-231125.yml
  tags: [RHEL-09-231125]
  when: supp_rules['RHEL-09-231125'] | default(true) | bool

- import_tasks: 231/RHEL-09-231130.yml
  tags: [RHEL-09-231130]
  when: supp_rules['RHEL-09-231130'] | default(true) | bool

- import_tasks: 231/RHEL-09-231135.yml
  tags: [RHEL-09-231135]
  when: supp_rules['RHEL-09-231135'] | default(true) | bool

- import_tasks: 231/RHEL-09-231140.yml
  tags: [RHEL-09-231140]
  when: supp_rules['RHEL-09-231140'] | default(true) | bool

- import_tasks: 231/RHEL-09-231145.yml
  tags: [RHEL-09-231145]
  when: supp_rules['RHEL-09-231145'] | default(true) | bool

- import_tasks: 231/RHEL-09-231150.yml
  tags: [RHEL-09-231150]
  when: supp_rules['RHEL-09-231150'] | default(true) | bool

- import_tasks: 231/RHEL-09-231155.yml
  tags: [RHEL-09-231155]
  when: supp_rules['RHEL-09-231155'] | default(true) | bool

- import_tasks: 231/RHEL-09-231160.yml
  tags: [RHEL-09-231160]
  when: supp_rules['RHEL-09-231160'] | default(true) | bool

- import_tasks: 231/RHEL-09-231165.yml
  tags: [RHEL-09-231165]
  when: supp_rules['RHEL-09-231165'] | default(true) | bool

- import_tasks: 231/RHEL-09-231170.yml
  tags: [RHEL-09-231170]
  when: supp_rules['RHEL-09-231170'] | default(true) | bool

- import_tasks: 231/RHEL-09-231175.yml
  tags: [RHEL-09-231175]
  when: supp_rules['RHEL-09-231175'] | default(true) | bool

- import_tasks: 231/RHEL-09-231180.yml
  tags: [RHEL-09-231180]
  when: supp_rules['RHEL-09-231180'] | default(true) | bool

- import_tasks: 231/RHEL-09-231185.yml
  tags: [RHEL-09-231185]
  when: supp_rules['RHEL-09-231185'] | default(true) | bool

- import_tasks: 231/RHEL-09-231190.yml
  tags: [RHEL-09-231190]
  when: supp_rules['RHEL-09-231190'] | default(true) | bool

- import_tasks: 231/RHEL-09-231200.yml
  tags: [RHEL-09-231200]
  when: supp_rules['RHEL-09-231200'] | default(true) | bool

- import_tasks: 232/RHEL-09-232010.yml
  tags: [RHEL-09-232010]
  when: supp_rules['RHEL-09-232010'] | default(true) | bool

- import_tasks: 232/RHEL-09-232015.yml
  tags: [RHEL-09-232015]
  when: supp_rules['RHEL-09-232015'] | default(true) | bool

- import_tasks: 232/RHEL-09-232020.yml
  tags: [RHEL-09-232020]
  when: supp_rules['RHEL-09-232020'] | default(true) | bool

- import_tasks: 232/RHEL-09-232035.yml
  tags: [RHEL-09-232035]
  when: supp_rules['RHEL-09-232035'] | default(true) | bool

- import_tasks: 232/RHEL-09-232040.yml
  tags: [RHEL-09-232040]
  when: supp_rules['RHEL-09-232040'] | default(true) | bool

- import_tasks: 232/RHEL-09-232045.yml
  tags: [RHEL-09-232045]
  when: supp_rules['RHEL-09-232045'] | default(true) | bool

- import_tasks: 232/RHEL-09-232050.yml
  tags: [RHEL-09-232050]
  when: supp_rules['RHEL-09-232050'] | default(true) | bool

- import_tasks: 232/RHEL-09-232103.yml
  tags: [RHEL-09-232103]
  when: supp_rules['RHEL-09-232103'] | default(true) | bool

- import_tasks: 232/RHEL-09-232104.yml
  tags: [RHEL-09-232104]
  when: supp_rules['RHEL-09-232104'] | default(true) | bool

- import_tasks: 232/RHEL-09-232190.yml
  tags: [RHEL-09-232190]
  when: supp_rules['RHEL-09-232190'] | default(true) | bool

- import_tasks: 232/RHEL-09-232195.yml
  tags: [RHEL-09-232195]
  when: supp_rules['RHEL-09-232195'] | default(true) | bool

- import_tasks: 232/RHEL-09-232200.yml
  tags: [RHEL-09-232200]
  when: supp_rules['RHEL-09-232200'] | default(true) | bool

- import_tasks: 232/RHEL-09-232205.yml
  tags: [RHEL-09-232205]
  when: supp_rules['RHEL-09-232205'] | default(true) | bool

- import_tasks: 232/RHEL-09-232210.yml
  tags: [RHEL-09-232210]
  when: supp_rules['RHEL-09-232210'] | default(true) | bool

- import_tasks: 232/RHEL-09-232215.yml
  tags: [RHEL-09-232215]
  when: supp_rules['RHEL-09-232215'] | default(true) | bool

- import_tasks: 232/RHEL-09-232220.yml
  tags: [RHEL-09-232220]
  when: supp_rules['RHEL-09-232220'] | default(true) | bool

- import_tasks: 232/RHEL-09-232225.yml
  tags: [RHEL-09-232225]
  when: supp_rules['RHEL-09-232225'] | default(true) | bool

- import_tasks: 232/RHEL-09-232230.yml
  tags: [RHEL-09-232230]
  when: supp_rules['RHEL-09-232230'] | default(true) | bool

- import_tasks: 232/RHEL-09-232235.yml
  tags: [RHEL-09-232235]
  when: supp_rules['RHEL-09-232235'] | default(true) | bool

- import_tasks: 232/RHEL-09-232240.yml
  tags: [RHEL-09-232240]
  when: supp_rules['RHEL-09-232240'] | default(true) | bool

- import_tasks: 232/RHEL-09-232245.yml
  tags: [RHEL-09-232245]
  when: supp_rules['RHEL-09-232245'] | default(true) | bool

- import_tasks: 232/RHEL-09-232250.yml
  tags: [RHEL-09-232250]
  when: supp_rules['RHEL-09-232250'] | default(true) | bool

- import_tasks: 232/RHEL-09-232255.yml
  tags: [RHEL-09-232255]
  when: supp_rules['RHEL-09-232255'] | default(true) | bool

- import_tasks: 232/RHEL-09-232260.yml
  tags: [RHEL-09-232260]
  when: supp_rules['RHEL-09-232260'] | default(true) | bool

- import_tasks: 251/RHEL-09-251020.yml
  tags: [RHEL-09-251020]
  when: supp_rules['RHEL-09-251020'] | default(true) | bool

- import_tasks: 251/RHEL-09-251035.yml
  tags: [RHEL-09-251035]
  when: supp_rules['RHEL-09-251035'] | default(true) | bool

- import_tasks: 251/RHEL-09-251040.yml
  tags: [RHEL-09-251040]
  when: supp_rules['RHEL-09-251040'] | default(true) | bool

- import_tasks: 252/RHEL-09-252020.yml
  tags: [RHEL-09-252020]
  when: supp_rules['RHEL-09-252020'] | default(true) | bool

- import_tasks: 252/RHEL-09-252035.yml
  tags: [RHEL-09-252035]
  when: supp_rules['RHEL-09-252035'] | default(true) | bool

- import_tasks: 252/RHEL-09-252045.yml
  tags: [RHEL-09-252045]
  when: supp_rules['RHEL-09-252045'] | default(true) | bool

- import_tasks: 252/RHEL-09-252050.yml
  tags: [RHEL-09-252050]
  when: supp_rules['RHEL-09-252050'] | default(true) | bool

- import_tasks: 252/RHEL-09-252060.yml
  tags: [RHEL-09-252060]
  when: supp_rules['RHEL-09-252060'] | default(true) | bool

- import_tasks: 252/RHEL-09-252070.yml
  tags: [RHEL-09-252070]
  when: supp_rules['RHEL-09-252070'] | default(true) | bool

- import_tasks: 252/RHEL-09-252075.yml
  tags: [RHEL-09-252075]
  when: supp_rules['RHEL-09-252075'] | default(true) | bool

- import_tasks: 255/RHEL-09-255064.yml
  tags: [RHEL-09-255064]
  when: supp_rules['RHEL-09-255064'] | default(true) | bool

- import_tasks: 255/RHEL-09-255065.yml
  tags: [RHEL-09-255065]
  when: supp_rules['RHEL-09-255065'] | default(true) | bool

- import_tasks: 255/RHEL-09-255070.yml
  tags: [RHEL-09-255070]
  when: supp_rules['RHEL-09-255070'] | default(true) | bool

- import_tasks: 255/RHEL-09-255075.yml
  tags: [RHEL-09-255075]
  when: supp_rules['RHEL-09-255075'] | default(true) | bool

- import_tasks: 255/RHEL-09-255115.yml
  tags: [RHEL-09-255115]
  when: supp_rules['RHEL-09-255115'] | default(true) | bool

- import_tasks: 255/RHEL-09-255120.yml
  tags: [RHEL-09-255120]
  when: supp_rules['RHEL-09-255120'] | default(true) | bool

- import_tasks: 255/RHEL-09-255125.yml
  tags: [RHEL-09-255125]
  when: supp_rules['RHEL-09-255125'] | default(true) | bool

- import_tasks: 271/RHEL-09-271010.yml
  tags: [RHEL-09-271010]
  when: supp_rules['RHEL-09-271010'] | default(true) | bool

- import_tasks: 271/RHEL-09-271015.yml
  tags: [RHEL-09-271015]
  when: supp_rules['RHEL-09-271015'] | default(true) | bool

- import_tasks: 271/RHEL-09-271020.yml
  tags: [RHEL-09-271020]
  when: supp_rules['RHEL-09-271020'] | default(true) | bool

- import_tasks: 271/RHEL-09-271025.yml
  tags: [RHEL-09-271025]
  when: supp_rules['RHEL-09-271025'] | default(true) | bool

- import_tasks: 271/RHEL-09-271030.yml
  tags: [RHEL-09-271030]
  when: supp_rules['RHEL-09-271030'] | default(true) | bool

- import_tasks: 271/RHEL-09-271035.yml
  tags: [RHEL-09-271035]
  when: supp_rules['RHEL-09-271035'] | default(true) | bool

- import_tasks: 271/RHEL-09-271040.yml
  tags: [RHEL-09-271040]
  when: supp_rules['RHEL-09-271040'] | default(true) | bool

- import_tasks: 271/RHEL-09-271045.yml
  tags: [RHEL-09-271045]
  when: supp_rules['RHEL-09-271045'] | default(true) | bool

- import_tasks: 271/RHEL-09-271050.yml
  tags: [RHEL-09-271050]
  when: supp_rules['RHEL-09-271050'] | default(true) | bool

- import_tasks: 271/RHEL-09-271055.yml
  tags: [RHEL-09-271055]
  when: supp_rules['RHEL-09-271055'] | default(true) | bool

- import_tasks: 271/RHEL-09-271060.yml
  tags: [RHEL-09-271060]
  when: supp_rules['RHEL-09-271060'] | default(true) | bool

- import_tasks: 271/RHEL-09-271065.yml
  tags: [RHEL-09-271065]
  when: supp_rules['RHEL-09-271065'] | default(true) | bool

- import_tasks: 271/RHEL-09-271070.yml
  tags: [RHEL-09-271070]
  when: supp_rules['RHEL-09-271070'] | default(true) | bool

- import_tasks: 271/RHEL-09-271075.yml
  tags: [RHEL-09-271075]
  when: supp_rules['RHEL-09-271075'] | default(true) | bool

- import_tasks: 271/RHEL-09-271080.yml
  tags: [RHEL-09-271080]
  when: supp_rules['RHEL-09-271080'] | default(true) | bool

- import_tasks: 271/RHEL-09-271085.yml
  tags: [RHEL-09-271085]
  when: supp_rules['RHEL-09-271085'] | default(true) | bool

- import_tasks: 271/RHEL-09-271090.yml
  tags: [RHEL-09-271090]
  when: supp_rules['RHEL-09-271090'] | default(true) | bool

- import_tasks: 271/RHEL-09-271095.yml
  tags: [RHEL-09-271095]
  when: supp_rules['RHEL-09-271095'] | default(true) | bool

- import_tasks: 271/RHEL-09-271100.yml
  tags: [RHEL-09-271100]
  when: supp_rules['RHEL-09-271100'] | default(true) | bool

- import_tasks: 271/RHEL-09-271105.yml
  tags: [RHEL-09-271105]
  when: supp_rules['RHEL-09-271105'] | default(true) | bool

- import_tasks: 271/RHEL-09-271110.yml
  tags: [RHEL-09-271110]
  when: supp_rules['RHEL-09-271110'] | default(true) | bool

- import_tasks: 271/RHEL-09-271115.yml
  tags: [RHEL-09-271115]
  when: supp_rules['RHEL-09-271115'] | default(true) | bool

- import_tasks: 271/RHEL-09-171011.yml
  tags: [RHEL-09-171011]
  when: supp_rules['RHEL-09-171011'] | default(true) | bool

- import_tasks: 291/RHEL-09-291030.yml
  tags: [RHEL-09-291030]
  when: supp_rules['RHEL-09-291030'] | default(true) | bool

- import_tasks: 291/RHEL-09-291040.yml
  tags: [RHEL-09-291040]
  when: supp_rules['RHEL-09-291040'] | default(true) | bool

- import_tasks: 411/RHEL-09-411015.yml
  tags: [RHEL-09-411015]
  when: supp_rules['RHEL-09-411015'] | default(true) | bool

- import_tasks: 411/RHEL-09-411025.yml
  tags: [RHEL-09-411025]
  when: supp_rules['RHEL-09-411025'] | default(true) | bool

- import_tasks: 411/RHEL-09-411030.yml
  tags: [RHEL-09-411030]
  when: supp_rules['RHEL-09-411030'] | default(true) | bool

- import_tasks: 411/RHEL-09-411035.yml
  tags: [RHEL-09-411035]
  when: supp_rules['RHEL-09-411035'] | default(true) | bool

- import_tasks: 411/RHEL-09-411040.yml
  tags: [RHEL-09-411040]
  when: supp_rules['RHEL-09-411040'] | default(true) | bool

- import_tasks: 411/RHEL-09-411045.yml
  tags: [RHEL-09-411045]
  when: supp_rules['RHEL-09-411045'] | default(true) | bool

- import_tasks: 411/RHEL-09-411050.yml
  tags: [RHEL-09-411050]
  when: supp_rules['RHEL-09-411050'] | default(true) | bool

- import_tasks: 411/RHEL-09-411055.yml
  tags: [RHEL-09-411055]
  when: supp_rules['RHEL-09-411055'] | default(true) | bool

- import_tasks: 411/RHEL-09-411060.yml
  tags: [RHEL-09-411060]
  when: supp_rules['RHEL-09-411060'] | default(true) | bool

- import_tasks: 411/RHEL-09-411065.yml
  tags: [RHEL-09-411065]
  when: supp_rules['RHEL-09-411065'] | default(true) | bool

- import_tasks: 411/RHEL-09-411070.yml
  tags: [RHEL-09-411070]
  when: supp_rules['RHEL-09-411070'] | default(true) | bool

- import_tasks: 411/RHEL-09-411095.yml
  tags: [RHEL-09-411095]
  when: supp_rules['RHEL-09-411095'] | default(true) | bool

- import_tasks: 411/RHEL-09-411100.yml
  tags: [RHEL-09-411100]
  when: supp_rules['RHEL-09-411100'] | default(true) | bool

- import_tasks: 411/RHEL-09-411110.yml
  tags: [RHEL-09-411110]
  when: supp_rules['RHEL-09-411110'] | default(true) | bool

- import_tasks: 412/RHEL-09-412035.yml
  tags: [RHEL-09-412035]
  when: supp_rules['RHEL-09-412035'] | default(true) | bool

- import_tasks: 412/RHEL-09-412080.yml
  tags: [RHEL-09-412080]
  when: supp_rules['RHEL-09-412080'] | default(true) | bool

- import_tasks: 431/RHEL-09-431016.yml
  tags: [RHEL-09-431016]
  when: supp_rules['RHEL-09-431016'] | default(true) | bool

- import_tasks: 431/RHEL-09-431020.yml
  tags: [RHEL-09-431020]
  when: supp_rules['RHEL-09-431020'] | default(true) | bool

- import_tasks: 432/RHEL-09-432020.yml
  tags: [RHEL-09-432020]
  when: supp_rules['RHEL-09-432020'] | default(true) | bool

- import_tasks: 432/RHEL-09-432025.yml
  tags: [RHEL-09-432025]
  when: supp_rules['RHEL-09-432025'] | default(true) | bool

- import_tasks: 432/RHEL-09-432030.yml
  tags: [RHEL-09-432030]
  when: supp_rules['RHEL-09-432030'] | default(true) | bool

- import_tasks: 432/RHEL-09-432035.yml
  tags: [RHEL-09-432035]
  when: supp_rules['RHEL-09-432035'] | default(true) | bool

- import_tasks: 433/RHEL-09-433016.yml
  tags: [RHEL-09-433016]
  when: supp_rules['RHEL-09-433016'] | default(true) | bool

- name: write supplement facts to disk
  copy:
    content: "{{ supp_facts | to_nice_json(indent=2) }}"
    dest: "{{ supp_facts_dir }}/{{ supp_run_ts }}-{{ inventory_hostname }}.json"
  delegate_to: localhost
  become: false
  tags: always
